schema_version = "1.0.0"

id = "optimize_your_project"
version = "0.7.61"
name = "Optimize Your Project"
tagline = "Remesh, LOD and static-mesh tools for Blender 4.2"
maintainer = "FISHHWB | Ded Zed"
type = "add-on"

website = "https://github.com/dedzedofficial/Optimize-Your-Project"
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 FISHHWB | Ded Zed",
]
